services:
  ai-tutor:
    build: .
    ports:
      - "8501:8501"
    environment:
      PORT: 8501
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    deploy:
      resources:
        reservations:
          memory: 512M
