name: Deploy to Defang

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Defang
        uses: DefangLabs/defang-github-action@v1.1.3
        with:
          compose-files: compose.yaml   # <-- change here
          mode: affordable
